name: Visions from Asheville
favicon: null
layout_spectrum: 0.48849
typography_spectrum: 0.11185
title: Visions from Asheville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37507409-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bbac92'
    - '#605743'
    - '#f0eeea'
    - '#2d415f'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
