name: Visions from Asheville
favicon: null
layout_spectrum: 0.48849
typography_spectrum: 0.11185
title: Visions from Asheville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37507409-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ddeef9'
    - '#c1a398'
    - '#936956'
    - '#472d24'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
