name: Visions from Asheville
favicon: null
layout_spectrum: 0.48849
typography_spectrum: 0.1394
title: Visions from Asheville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37507409-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1d1f'
    - '#cab8a3'
    - '#993d1c'
    - '#648e1d'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
