title: Visions from Asheville
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3125
  brandStrength: 0.450253
  lightness: 0.8125
  brandColors:
    - '#000000'
    - '#bbac92'
    - '#605743'
    - '#f0eeea'
    - '#2d415f'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-37507409-4
  facebook: null
name: Visions from Asheville
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1394
layout_spectrum: 0.48849
