name: Visions from Asheville
favicon: null
layout_spectrum: 0.49332
typography_spectrum: 0.07763
title: Visions from Asheville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37507409-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#212a22'
    - '#755a3f'
    - '#bd8d56'
    - '#e7be7a'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
