name: Visions from Asheville
favicon: null
layout_spectrum: 0.76711
typography_spectrum: 0.08097
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#212a22'
    - '#755a3f'
    - '#bd8d56'
    - '#e7be7a'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
