name: Visions from Asheville
favicon: null
layout_spectrum: 0.76043
typography_spectrum: 0.14535
title: Visions from Asheville sponsored by Asheville Visions Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3a'
    - '#ffff00'
    - '#ffffff'
    - '#ff0000'
    - '#d8b365'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
