name: Visions from Asheville
favicon: null
layout_spectrum: 0.7975184065289795
typography_spectrum: 0.05186117975972593
title: Visions from Asheville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3a'
    - '#ffff00'
    - '#ffffff'
    - '#ff0000'
    - '#d8b365'
  brandStrength: 0.75
  lightness: 0.4932594117708504
  saturation: 0.44550226419232786
  rhythmicContrast: 0.6787399046588689
purpose: []
