name: Visions from Asheville
favicon: null
layout_spectrum: 0.48849
typography_spectrum: 0.06761
title: Visions from Asheville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37507409-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7a7b5'
    - '#6b340d'
    - '#000000'
    - '#e3d2d2'
    - '#e0bb1c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
