name: Visions from Asheville
favicon: null
layout_spectrum: 0.48849
typography_spectrum: 0.15043
title: Visions from Asheville
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37507409-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#031d26'
    - '#414135'
    - '#6595c3'
    - '#c8af9f'
    - '#3771b7'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5252951
  rhythmicContrast: 0
purpose: []
